<?php

namespace Webkul\InventoryTransfer\Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AttributeSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        $now = Carbon::now();

        DB::table('attributes')
            ->insert([
                /**
                 * Inventory Transfer Attributes
                 */
                [
                    'code'            => 'increment_id',
                    'name'            => trans('inventory_transfer::app.seeders.attributes.inventory-transfers.increment-id'),
                    'type'            => 'text',
                    'entity_type'     => 'inventory_transfers',
                    'lookup_type'     => null,
                    'validation'      => null,
                    'sort_order'      => '1',
                    'is_required'     => '1',
                    'is_unique'       => '1',
                    'quick_add'       => '0',
                    'is_user_defined' => '0',
                    'created_at'      => $now,
                    'updated_at'      => $now,
                ], [
                    'code'            => 'reference_number',
                    'name'            => trans('inventory_transfer::app.seeders.attributes.inventory-transfers.reference-number'),
                    'type'            => 'text',
                    'entity_type'     => 'inventory_transfers',
                    'lookup_type'     => null,
                    'validation'      => null,
                    'sort_order'      => '2',
                    'is_required'     => '1',
                    'is_unique'       => '1',
                    'quick_add'       => '0',
                    'is_user_defined' => '0',
                    'created_at'      => $now,
                    'updated_at'      => $now,
                ], [
                    'code'            => 'status',
                    'name'            => trans('inventory_transfer::app.seeders.attributes.inventory-transfers.status'),
                    'type'            => 'text',
                    'entity_type'     => 'inventory_transfers',
                    'lookup_type'     => null,
                    'validation'      => null,
                    'sort_order'      => '3',
                    'is_required'     => '1',
                    'is_unique'       => '0',
                    'quick_add'       => '0',
                    'is_user_defined' => '0',
                    'created_at'      => $now,
                    'updated_at'      => $now,
                ], [
                    'code'            => 'from_warehouse_id',
                    'name'            => trans('inventory_transfer::app.seeders.attributes.inventory-transfers.from-warehouse'),
                    'type'            => 'select',
                    'entity_type'     => 'inventory_transfers',
                    'lookup_type'     => 'warehouses',
                    'validation'      => null,
                    'sort_order'      => '4',
                    'is_required'     => '1',
                    'is_unique'       => '0',
                    'quick_add'       => '0',
                    'is_user_defined' => '0',
                    'created_at'      => $now,
                    'updated_at'      => $now,
                ], [
                    'code'            => 'to_warehouse_id',
                    'name'            => trans('inventory_transfer::app.seeders.attributes.inventory-transfers.to-warehouse'),
                    'type'            => 'select',
                    'entity_type'     => 'inventory_transfers',
                    'lookup_type'     => 'warehouses',
                    'validation'      => null,
                    'sort_order'      => '5',
                    'is_required'     => '1',
                    'is_unique'       => '0',
                    'quick_add'       => '0',
                    'is_user_defined' => '0',
                    'created_at'      => $now,
                    'updated_at'      => $now,
                ], [
                    'code'            => 'shipping_method',
                    'name'            => trans('inventory_transfer::app.seeders.attributes.inventory-transfers.shipping-method'),
                    'type'            => 'text',
                    'entity_type'     => 'inventory_transfers',
                    'lookup_type'     => null,
                    'validation'      => null,
                    'sort_order'      => '6',
                    'is_required'     => '0',
                    'is_unique'       => '0',
                    'quick_add'       => '0',
                    'is_user_defined' => '0',
                    'created_at'      => $now,
                    'updated_at'      => $now,
                ], [
                    'code'            => 'tracking_number',
                    'name'            => trans('inventory_transfer::app.seeders.attributes.inventory-transfers.tracking-number'),
                    'type'            => 'text',
                    'entity_type'     => 'inventory_transfers',
                    'lookup_type'     => null,
                    'validation'      => null,
                    'sort_order'      => '7',
                    'is_required'     => '0',
                    'is_unique'       => '0',
                    'quick_add'       => '0',
                    'is_user_defined' => '0',
                    'created_at'      => $now,
                    'updated_at'      => $now,
                ], [
                    'code'            => 'expected_transfer_date',
                    'name'            => trans('inventory_transfer::app.seeders.attributes.inventory-transfers.expected-transfer-date'),
                    'type'            => 'date',
                    'entity_type'     => 'inventory_transfers',
                    'lookup_type'     => null,
                    'validation'      => null,
                    'sort_order'      => '8',
                    'is_required'     => '0',
                    'is_unique'       => '0',
                    'quick_add'       => '0',
                    'is_user_defined' => '0',
                    'created_at'      => $now,
                    'updated_at'      => $now,
                ], [
                    'code'            => 'total_items_count',
                    'name'            => trans('inventory_transfer::app.seeders.attributes.inventory-transfers.total-items-count'),
                    'type'            => 'text',
                    'entity_type'     => 'inventory_transfers',
                    'lookup_type'     => null,
                    'validation'      => 'numeric',
                    'sort_order'      => '9',
                    'is_required'     => '0',
                    'is_unique'       => '0',
                    'quick_add'       => '0',
                    'is_user_defined' => '0',
                    'created_at'      => $now,
                    'updated_at'      => $now,
                ], [
                    'code'            => 'total_qty_requested',
                    'name'            => trans('inventory_transfer::app.seeders.attributes.inventory-transfers.total-qty-requested'),
                    'type'            => 'text',
                    'entity_type'     => 'inventory_transfers',
                    'lookup_type'     => null,
                    'validation'      => 'numeric',
                    'sort_order'      => '10',
                    'is_required'     => '0',
                    'is_unique'       => '0',
                    'quick_add'       => '0',
                    'is_user_defined' => '0',
                    'created_at'      => $now,
                    'updated_at'      => $now,
                ], [
                    'code'            => 'total_qty_received',
                    'name'            => trans('inventory_transfer::app.seeders.attributes.inventory-transfers.total-qty-received'),
                    'type'            => 'text',
                    'entity_type'     => 'inventory_transfers',
                    'lookup_type'     => null,
                    'validation'      => 'numeric',
                    'sort_order'      => '11',
                    'is_required'     => '0',
                    'is_unique'       => '0',
                    'quick_add'       => '0',
                    'is_user_defined' => '0',
                    'created_at'      => $now,
                    'updated_at'      => $now,
                ], [
                    'code'            => 'created_by_user_id',
                    'name'            => trans('inventory_transfer::app.seeders.attributes.inventory-transfers.created-by'),
                    'type'            => 'select',
                    'entity_type'     => 'inventory_transfers',
                    'lookup_type'     => 'users',
                    'validation'      => null,
                    'sort_order'      => '12',
                    'is_required'     => '1',
                    'is_unique'       => '0',
                    'quick_add'       => '0',
                    'is_user_defined' => '0',
                    'created_at'      => $now,
                    'updated_at'      => $now,
                ], [
                    'code'            => 'assigned_to_user_id',
                    'name'            => trans('inventory_transfer::app.seeders.attributes.inventory-transfers.assigned-to'),
                    'type'            => 'select',
                    'entity_type'     => 'inventory_transfers',
                    'lookup_type'     => 'users',
                    'validation'      => null,
                    'sort_order'      => '13',
                    'is_required'     => '0',
                    'is_unique'       => '0',
                    'quick_add'       => '0',
                    'is_user_defined' => '0',
                    'created_at'      => $now,
                    'updated_at'      => $now,
                ],
            ]);
    }
}
